name: 'Flutter Versioning'
description: 'Sets the flutter version and build number in the provided targets.'
inputs:
  pubspec_path:
    description: 'Path to the pubspec.yaml to update'
    required: true
outputs:
  new_version:
    description: 'The version that was written to the pubspec.yaml'
  new_build: # output will be available to future steps
    description: 'The build number that was written to the pubspec.yaml'
runs:
  using: 'node16'
  main: 'dist/index.js'
